### ISSUE TITLE
Update Infrastructure

### ISSUE THREAD

**Issue by haydar-metin** [borkdominik/bigUML#60]
- [x] Update to latest versions (dependencies)
  * Check how operation handlers (create,delete, edit)  / action handlers work in the newest version
- [ ] Add Linter (Java missing) and Code Formatter 
  * Config for Typescript can be taken from the [GLSP Repo](https://github.com/eclipse-glsp/glsp/tree/master/packages)
- [ ] Use SCSS
- [ ] Use Printer for client (*.ts)

## Future

- [ ] Make the project cross IDE friendly by moving to a pure maven build and dependency management
  * Add support to docker + vscode remote
