### ISSUE TITLE
Refactor code in UML project

### ISSUE THREAD

**Issue by haydar-metin** [borkdominik/bigUML#61]
- [x] Put diagram code into own packages
- [x] Disconnect all diagram types and work on them incrementally  
  * Start with Communication Diagram as demo
- [x] Divide between core code (i.e. code independent of diagram types) and diagram types
  * Dependency Injection based features (core has only access to interfaces / tokens)
  * ~Use Injection (Annotation) for loading the uml diagram type~
- [x] Communicate as far as possible with interfaces, even GLSP -> ModelServer
- [x] Change on how OperationHandlers are implemented (no switch, if, instanceof!)
- [x] Clean up code (DRY)
   * ~GModel (*Factory classes)~
   * ~Handlers~
   * ~ModelServerAccess~
   * ~Utils~
   * ~Palette~
   * ~UmlConfig~

TODO: 

- [ ] Check how icons are rendered (path problems, dark and light icons, some images are not used)
