### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by haydar-metin** [borkdominik/bigUML#70]
## Basic

- [x] Crud Operations 

## Enhancements

- [x] #32
- [x] #33
- [ ] #34
- [ ] Allow re-parenting of elements
- [x] Allow reordering of attributes / enumerations etc.
- [x] Use SVG Icons

## Features

- [x] Outline
- [X] Property Palette 
- [ ] Validation
- [x] Reconnect edges
- [x] Hover

## Bugs

- [x] #51 
- [x] Generalization also not deletable anymore

## Missing

- [ ] Class Templates
- [ ] [Association Qualifier](https://www.uml-diagrams.org/property.html#qualifier)
- [ ] [Operation](https://www.uml-diagrams.org/operation.html) - Operation Properties
- [ ] [Constraint](https://www.uml-diagrams.org/constraint.html?context=class-diagrams)
- [ ] [Multiplicity](https://www.uml-diagrams.org/multiplicity.html) unique / ordered
- [ ] [Association](https://www.uml-diagrams.org/association.html) - Ternary, Ownership of Association End, Association Navigability

**Comment by haydar-metin** [comment]
Feedback from 17.05.2023

### Class

- [ ] No visibility label (+, -) in the header (it is not in the specification)
- [ ] <<Abstract>> should be {Abstract} or should show nothing (see specification)
- [ ] "Owned" prefix is not necessary for the properties palette

### Association

- [ ] Add visibility (public, private) on the member end
- [ ] Add source/target label in the property palette to differentiate between the ends
- [ ] The default value for the member end name should be empty
- [ ] Use navigatable property "<><--x-" (<-, x part) (i.e., if the member can be navigated from the other side)
- [ ] Add {xor} element
- [ ] Add {unique/non-unique} property

### Properties

- [ ] Do not render default values, for example, multiplicity 1 or [1]
- [ ] Add predefined types like String, Int, Double (remove the necessity to create them manually in the file)
- [ ] Allow creating the new type on the fly without creating it before
	- use a free text input + dropdown combination  [____⌄]
	- Dropdown: Select predefined + elements available in the diagram
	- Input Text: Search or create a new type
	- Smart Automation: Ask the user if it wants to create the typed name as a new class


### N-Relationships

- [ ] Allow creating n-ary relationships
	- e.g., create a node <> and draw the edges (e.g., associations) from it to the other nodes
